%%% makeManualMasks.m
%%% Wrapper to make an axon mask
%%%
%%% Input arguments
%%% gFileIn = maximum projection file of green color channel
%%% rFileIn = maximum projection file of green color channel.  If you don't
%%%      want to trace a red image, just enter a bogus, nonexistent filename and
%%%      this will be ignored
%%% maskFile = csv mask file generated by makeMask
%%% numLineScans = number of line scans to collect.  This parameter was hardly used
%%%      and hence not thoroughly tested
%%% diPix = number of pixels by which to dilate the user-selected line
%%%
%%% Output argument
%%% alignedR = aligned red channel image

function alignedR = makeManualMasks(gFileIn,rFileIn,maskFile,numLineScans,diPix)

if ~exist('diPix','var') || isempty(diPix)
    diPix = 30;
end

gIn = imread(gFileIn);

g1 = gIn - mean(gIn(:));
if exist(rFileIn,'file')
    rIn = imread(rFileIn);
    r1 = rIn - mean(rIn(:));
    [~,alignedR] = alignImages(g1,r1);
    imToShow = cat(3,linRescale(alignedR)*8,linRescale(g1)*4,zeros(size(g1)));
else
    rIn = [];
    imToShow = linRescale(g1)*4;
end
figure(1);imshow(imToShow);

s = input('Do you want to trace an axon? (lowercase "n" for no) ','s');
if s ~= 'n'
    makeMaskLoop(gIn,rIn,diPix,maskFile,[],[],numLineScans);
end
